# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - goos:
      - linux
      - darwin
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.Revision={{.Commit}}
      - -X github.com/prometheus/common/version.Branch=master
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
      - -X github.com/prometheus/common/version.BuildUser={{.Env.USER}}
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    id: binary
    main: .
    binary: credhub_exporter
archives:
  - id: zip-archive-provider
    builds: [binary]
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format: zip
  - id: binary-archive-provider
    builds: [binary]
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
